apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: backend
          image: immihubacr.azurecr.io/immihub-be:latest
          imagePullPolicy: Always
          env:
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DJANGO_SETTINGS_MODULE
              value: "meraki.settings"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: DEBUG
              value: "True"
          ports:
            - containerPort: 8000
